server:
  port: 9999
  ssl:
    enabled: true
    key-alias: XYZabc123YES
    key-store: classpath:certs/keystore.pk12
    key-store-type: PKCS12
    key-store-password: XYZabc123YES
    key-password: XYZabc123YES